### ISSUE TITLE
Doc build fails due to old Sphinx

### ISSUE THREAD

**Issue by kloczek** [abhinavsingh/proxy.py#1356]
Looks like something is wrong and documentation build fails.
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.1.2
making output directory... done
loading intersphinx inventory from https://myst-parser.rtfd.io/en/latest/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.python.org/2/objects.inv...
intersphinx inventory has moved: https://myst-parser.rtfd.io/en/latest/objects.inv -> https://myst-parser.readthedocs.io/en/latest/objects.inv
myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'replacements', 'substitution', 'html_image', 'colon_fence', 'deflist', 'html_admonition', 'smartquotes'}, disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=3, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={project: ..., release: ..., release_l: ..., version: ...}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.__main__.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.proxy.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common._scm_version.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common._version.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.backports.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.constants.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.flag.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.logger.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.pki.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.plugins.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.types.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.utils.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.common.version.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.acceptor.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.acceptor.acceptor.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.acceptor.pool.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.base.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.base.tcp_server.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.base.tcp_tunnel.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.base.tcp_upstream.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.connection.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.connection.client.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.connection.connection.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.connection.pool.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.connection.server.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.connection.types.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.event.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.event.dispatcher.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.event.manager.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.event.names.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.event.queue.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.event.subscriber.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.listener.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.listener.base.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.listener.pool.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.listener.tcp.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.listener.unix.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.ssh.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.ssh.handler.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.ssh.listener.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.tls.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.tls.certificate.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.tls.finished.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.tls.handshake.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.tls.hello.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.tls.key_exchange.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.tls.pretty.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.tls.tls.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.tls.types.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.delegate.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.local.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.pool.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.remote.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.threaded.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.threadless.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.work.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.fd.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.fd.fd.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.fd.local.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.fd.remote.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.task.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.task.handler.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.task.local.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.task.remote.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.core.work.task.task.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.dashboard.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.dashboard.dashboard.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.codes.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.connection.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.descriptors.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.handler.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.headers.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.methods.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.plugin.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.protocols.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.responses.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.url.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.exception.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.exception.base.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.exception.http_request_rejected.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.exception.proxy_auth_failed.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.exception.proxy_conn_failed.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.inspector.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.inspector.devtools.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.inspector.inspect_traffic.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.inspector.transformer.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.parser.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.parser.chunk.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.parser.parser.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.parser.protocol.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.parser.types.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.proxy.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.proxy.auth.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.proxy.plugin.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.proxy.server.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.server.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.server.middleware.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.server.pac_plugin.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.server.plugin.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.server.protocols.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.server.reverse.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.server.web.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.websocket.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.websocket.client.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.websocket.frame.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.websocket.plugin.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.http.websocket.transport.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.cloudflare_dns.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.custom_dns_resolver.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.filter_by_client_ip.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.filter_by_upstream.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.filter_by_url_regex.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.man_in_the_middle.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.mock_rest_api.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.modify_chunk_response.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.modify_post_data.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.program_name.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.proxy_pool.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.redirect_to_custom_server.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.reverse_proxy.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.shortlink.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.plugin.web_server_route.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.socks.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.socks.client.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.socks.handler.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.socks.operations.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/proxy.socks.packet.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/proxy.py-2.4.3/docs/pkg/modules.rst.
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/ext.py", line 363, in get_outdated_docs
    towncrier_fragment_paths = _lookup_towncrier_fragments(
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/ext.py", line 132, in _lookup_towncrier_fragments
    fragment_base_directory = project_path / towncrier_config['directory']
TypeError: 'Config' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 290, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 287, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 381, in read
    for docs in self.events.emit('env-get-outdated', self.env, added, changed, removed):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <bound method TowncrierDraftEntriesEnvironmentCollector.get_outdated_docs of <sphinxcontrib.towncrier.ext.TowncrierDraftEntriesEnvironmentCollector object at 0x7f2436381970>> for event 'env-get-outdated' threw an exception (exception: 'Config' object is not subscriptable)

Extension error (sphinxcontrib.towncrier.ext):
Handler <bound method TowncrierDraftEntriesEnvironmentCollector.get_outdated_docs of <sphinxcontrib.towncrier.ext.TowncrierDraftEntriesEnvironmentCollector object at 0x7f2436381970>> for event 'env-get-outdated' threw an exception (exception: 'Config' object is not subscriptable)
```
</details>

<details>
<summary>List of installed modules in build env:</summary>

```console
Package                       Version
----------------------------- -------
alabaster                     0.7.13
Babel                         2.14.0
build                         1.0.3
charset-normalizer            3.3.2
click                         8.1.7
cppclean                      0.13
distro                        1.8.0
dnf                           4.18.2
docutils                      0.20.1
exceptiongroup                1.1.3
gpg                           1.23.2
idna                          3.6
imagesize                     1.4.1
importlib-metadata            7.0.1
importlib-resources           6.1.1
incremental                   22.10.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.2
libdnf                        0.72.0
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
mdit-py-plugins               0.4.0
mdurl                         0.1.2
myst-parser                   2.0.0
packaging                     23.2
pbr                           5.11.1
pluggy                        1.3.0
Pygments                      2.17.2
pyproject_hooks               1.0.0
pytest                        7.4.3
python-dateutil               2.8.2
pytz                          2023.3
PyYAML                        6.0.1
requests                      2.31.0
setuptools                    69.0.3
setuptools-scm                8.0.4
setuptools-scm-git-archive    1.4
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        7.1.2
sphinxcontrib-apidoc          0.3.0
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.5
sphinxcontrib-htmlhelp        2.0.4
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.9
sphinxcontrib-towncrier       0.3.1a3
tomli                         2.0.1
towncrier                     23.11.0
typing_extensions             4.9.0
urllib3                       1.26.18
wheel                         0.42.0
zipp                          3.17.0
```
</details>

**Comment by abhinavsingh** [comment]
@kloczek This has now been fixed, due to stale nature of the repository, workflows started to fail due to upstream changes.  This has now been fixed in the `develop` branch

**Comment by kloczek** [comment]
Just tested 2.4.4 and issue still is not resolved.
Here is the patch
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -209,11 +209,11 @@
 # -- Options for extlinks extension ------------------------------------------

 extlinks = {
-    'issue': (f'{github_repo_url}/issues/%s', '#'),  # noqa: WPS323
-    'pr': (f'{github_repo_url}/pull/%s', 'PR #'),  # noqa: WPS323
-    'commit': (f'{github_repo_url}/commit/%s', ''),  # noqa: WPS323
+    'issue': (f'{github_repo_url}/issues/%s', '#%s'),  # noqa: WPS323
+    'pr': (f'{github_repo_url}/pull/%s', 'PR #%s'),  # noqa: WPS323
+    'commit': (f'{github_repo_url}/commit/%s', '%s'),  # noqa: WPS323
     'gh': (f'{github_url}/%s', 'GitHub: '),  # noqa: WPS323
-    'user': (f'{github_sponsors_url}/%s', '@'),  # noqa: WPS323
+    'user': (f'{github_sponsors_url}/%s', '@%s'),  # noqa: WPS323
 }

 # -- Options for linkcheck builder -------------------------------------------
```
Please let me know if you want this patch as PR.

**Comment by kloczek** [comment]
Just FTR https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html

**Comment by kloczek** [comment]
BTW it would be good to drop python<=3.7 support by filter all code over 'pyupgrade --py38-plus`.

**Comment by abhinavsingh** [comment]
@kloczek Thank you for checking back on it.  Can you please share your machine/OS details so that I can try to reproduce the same.  A PR will certainly be of great help 👍

I agree at some point we might have to drop support for outdating py3 versions.   But IIUC, `proxy.py` cannot drop support for <= 3.7 because several dependants use `proxy.py` for exactly this reason.  Also FWIW, we have workflows/tests for <=3.7 and they seem to be holding on for now :D

**Comment by kloczek** [comment]
> Can you please share your machine/OS details

This issue has nothing to do with machine/OS details. This issue is ONLY related to used `sphinx`.
In this case I'm using `sphinx` 7.2.6.

**Comment by abhinavsingh** [comment]
> > Can you please share your machine/OS details
> 
> This issue has nothing to do with machine/OS details. This issue is ONLY related to used `sphinx`. In this case I'm using `sphinx` 7.2.6.

Which means you are not using versions pinned by `proxy.py` and likely hence the issue.   Under `docs/requirements.txt` we have `sphinx==4.3.2`

Try `make lib-doc` , lemme know if this helps.

**Comment by kloczek** [comment]
This +3 years old version is no longer supported by any Linux/*BSD/Solaris distro.
